name: DevSecOps Security Pipeline

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Gitleaks (Secrets Scan)
        uses: gitleaks/gitleaks-action@v2

      - name: Run Semgrep (SAST)
        uses: returntocorp/semgrep-action@v1

      - name: Run Safety (Dependencies Scan)
        run: |
          pip install safety
          safety check -r requirements.txt

      - name: Run Trivy FS Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          severity: CRITICAL,HIGH

      - name: Build Docker image
        run: docker build -t devsecops-app .

      - name: Run Trivy Image Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: devsecops-app
          severity: CRITICAL,HIGH
