name: DevSecOps Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Gitleaks Scan
        uses: zricethezav/gitleaks-action@v2

      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1

      - name: Trivy Scan (Filesystem)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'

      # 🔥 AQUI entra o upgrade
      - name: Build Docker Image
        run: docker build -t test-app .

      - name: Scan Docker Image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'test-app'
